spring.application.name=biblioteca
server.port=8080
server.address=0.0.0.0

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/biblioteca}

spring.web.resources.add-mappings=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.base.url=${APP_BASE_URL:http://localhost:8080}

sibu.cover.default-url=https://via.placeholder.com/300x450?text=Sin+Portada
sibu.storage.path=./uploads
